#################################################################################
# Tractus-X - Industry Flag Service
#
# Copyright (c) 2025 CGI Deutschland B.V. & Co. KG
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

authorization:
  enabled: true
  apiKey:
    key: "X-Api-Key"
    value: ifs-api-key

flags:
  - industry: chemicals

  - industry: automotive
    mimetype: application/json
    proof: >
      {
        "result": true
      }

startup:
  checks: False
  refresh_interval: 10

ifs:
  ## Refresh interval for the cache of applications
  refresh_interval: 1440
  ## DCT Type used to find the applications in the cache
  dct_type: "IndustryFlagService"
  ## JSON array of policies that are allowed to be used
  policies: |-
    [
      {
        "odrl:permission": {
            "odrl:action": {
                "@id": "odrl:use"
            },
            "odrl:constraint": {
              "odrl:leftOperand": {
                  "@id": "cx-policy:UsagePurpose"
              },
              "odrl:operator": {
                  "@id": "odrl:eq"
              },
              "odrl:rightOperand": "catenax.industryflagservice"
          }
        },
        "odrl:prohibition": [],
        "odrl:obligation": []
      }
    ]


edc:
  url: "https://TODO___XXX__YOUR_URL___XXX"
  apis:
    readiness: "/api/check/readiness"
    catalog: "/control/data/v3/catalog/request"
    edr_prefix: "/control/data/v2/edrs"
    view_edr: "/request"
    transfer_edr: "/dataaddress?auto_refresh=true"
    dsp: "/control/api/v1/dsp"

  oauth:
    token_url: "https://TODO___XXX__YOUR_URL___XXX"
    client_id: "TODO___XXX___YOUR_ID___XXX"
    client_secret: "TODO___XXX___YOUR_SECRET___XXX"

  participantId: "BPNL00000009VAL7"
  
  dct_type_key: "'http://purl.org/dc/terms/type'.'@id'"

  cache:
    expiration_time: 60

discovery:
  url: "https://discoveryfinder.beta.cofinity-x.com/api/v1.0/administration/connectors/discovery/search"
  keys:
    edc_discovery: "bpnl"

catenax:
  centralidp:
    url: "https://centralidp.beta.cofinity-x.com/auth/"
    realm: CX-Central
    clientid: "TODO___XXX__YOUR_CLIENTID___XXX"
    clientsecret: "TODO___XXX___YOUR_CLIENT_SECRET___XXX"
